# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
name: "Dependabot auto-merge"

on: [pull_request_target] # yamllint disable-line rule:truthy

permissions: write-all

jobs:
  dependabot:
    runs-on: "ubuntu-latest"
    if: "${{ github.actor == 'dependabot[bot]' }}"
    steps:
      - name: "Dependabot metadata"
        id: "metadata"
        uses: "dependabot/fetch-metadata@v1.3.6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Enable auto-merge for Dependabot PRs"
        if: "${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}"
        run: "gh pr merge --auto --merge \"$PR_URL\""
        env:
          PR_URL: "${{github.event.pull_request.html_url}}"
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
